name: virtual_scroll_demo
description: virtual-scroll demo for AngularDart
version: 0.2.1
environment:
  sdk: '>=2.0.0-dev.69.0 <3.0.0'
dependencies:
  angular: ^5.0.0-beta
  virtual_scroll:
    git:
      url: https://github.com/takutaro/angular-virtual-scroll.git

dev_dependencies:
  angular_test:
  build_runner:
  build_test:
  build_web_compilers:
  test: