name: virtual_scroll_demo
description: virtual-scroll demo for AngularDart
version: 0.0.4
environment:
  sdk: '>=1.24.0 <2.0.0'
dependencies:
  angular: ^4.0.0
  http: ^0.11.3
  stream_transformers: ^0.3.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.2
  virtual_scroll:
    # path: /home/taku/workspace/angular-virtual-scroll
    git: https://github.com/takutaro/angular-virtual-scroll.git
web:
  compiler:
    debug: dartdevc
    release: dart2js
transformers:
- angular:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
